- name: setup DNS in HOL
  copy: src=resolv.conf dest=/etc/resolv.conf

- name: disable DHClient for request DNS info
  copy: src=dhclient.conf dest=/etc/dhcp/dhclient.conf 

- name: add DNS into resolvconf base
  copy: src=resolv.conf.base dest=/etc/resolvconf/resolv.conf.d/base

- name: add .ssh directory for root
  file: path=/root/.ssh state=directory mode=0600 

- name: copy authenication_key for lab-desktop
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys mode=0600

- name: set hostname in hostname file 
  template: src=etc/hostname.j2 dest=/etc/hostname

- name: copy hosts for environment
  template: src=etc/hosts.j2 dest=/etc/hosts

- name: set hostname of node 
  command: hostname {{ node_host_name }}

- name: configure interface file for multiple interfaces
  template: src=etc/network/interfaces.j2 dest=/etc/network/interfaces

- name: run apt-get upgrade
  apt: upgrade=dist update_cache=yes

- name: reboot system
  command: reboot now
