- name: setting PBR eth0
  lineinfile: dest=/etc/iproute2/rt_tables line='200 eth0'

- name: setting PBR eth1
  lineinfile: dest=/etc/iproute2/rt_tables line='201 eth1'

- name: configure networking with PBR
  template: src=etc/network/interfaces dest=/etc/network/interfaces
      backup=yes
  notify: restart networking

#update keepalived
- name: update keepalived config
  template: src=etc/keepalived/keepalived.conf dest=/etc/keepalived/keepalived.conf
        owner=root group=root backup=yes

- name: update update haproxy.cfg
  template: src=etc/haproxy/haproxy.cfg dest=/etc/haproxy/haproxy.cfg
        owner=root group=root backup=yes

- name: force restart
  command: echo ""
  notify: restart LB services
