- name: setting PBR eth0
  lineinfile: dest=/etc/iproute2/rt_tables line='200 eth0'

- name: setting PBR eth1
  lineinfile: dest=/etc/iproute2/rt_tables line='201 eth1'

- name: configure networking with PBR
  template: src=etc/network/interfaces.j2 dest=/etc/network/interfaces backup=yes
  notify: restart networking

- name: update keepalived config
  template: src=etc/keepalived/keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf owner=root group=root backup=yes

- name: force restart
  command: echo ""
  notify: restart keepalived 

- name: update update haproxy.cfg
  template: src=etc/haproxy/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root backup=yes

- name: force restart
  command: echo ""
  notify: restart haproxy 
