- name: install cloud archive kilo release
  apt_repository: repo:'cloud-archive:kilo'

- name: run apt-get update
  apt: update_cache=yes
  ignore_errors: yes

- name: run apt-get upgrade
  apt: upgrade=dist
