---
- name: create group
  group: name=neutron state=present

- name: create user
  user: name=neutron shell=/bin/false group=neutron home=/var/lib/neutron

- name: run apt-get update
  apt: update_cache=yes
  ignore_errors: yes

- name: install openstack neutron software packages
  apt: pkg={{ item }} state=latest
  with_items:
  - neutron-server 
  - neutron-plugin-ml2 
  - neutron-plugin-openvswitch-agent 
  - neutron-l3-agent 
  - neutron-dhcp-agent 
  - neutron-metadata-agent
  - neutron-lbaas-agent
  - python-neutronclient

- name: change owner:group for /etc/neutron
  file: path=/etc/neutron owner=neutron group=neutron state=directory recurse=yes

- name: remove SQLite database
  file: path=/var/lib/neutron/neutron.sqlite state=absent
