- name: download and RabbitMQ repository key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present validate_certs=no

- name: add RabbitMQ repository 
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present update_cache=yes

- name: run apt-get update
  apt: update_cache=yes
  ignore_errors: yes

- name: run apt-get upgrade
  apt: upgrade=dist

- name: install RabbitMQ
  apt: pkg={{ item }} state=latest
  with_items:
  - rabbitmq-server
