- name: Remove existing InnoDB log files
  file: path=/var/lib/mysql/{{ item }} state=absent
  with_items:
  - ib_logfile0
  - ib_logfile1
 
- name: copy my.cnf
  copy: src=my.cnf dest=/etc/mysql/my.cnf
  notify: restart mysql
