- name: add keystone endpoint information
  keystone_service: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    region: "{{ openstack_region }}"
    name: keystone
    type: identity
    description: "Identity Service"
    public_url: "{{ keystone_public_url }}"
    internal_url: "{{ keystone_internal_url }}"
    admin_url: "{{ keystone_admin_url }}"

- name: create admin tenant
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: admin
    tenant_description: "Admin Tenant"

- name: create admin user
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: admin
    user: admin 
    password: "{{ tenant_admin_password }}"

- name: create admin role and associate it with admin user
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: admin
    user: admin 
    role: admin

- name: create Member role and associate it with admin user
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: admin
    user: admin 

