- name: Configure keystone
  template: src=etc/keystone/keystone.conf.j2 dest=/etc/keystone/keystone.conf

- name: Perform a Keystone DB sync
  command: keystone-manage db_sync

- name: remove SQLite DB
  file: path=/var/lib/keystone/keystone.db state=absent
