- name: Configure nova
  template: src=etc/nova/nova.conf.j2 dest=/etc/nova/nova.conf

- name: Perform a Nova DB sync
  command: nova-manage db_sync

- name: Restart Nova Services
  service: name=nova-api state=restarted
  service: name=nova-cert state=restarted
  service: name=nova-consoleauth state=restarted
  service: name=nova-scheduler state=restarted
  service: name=nova-conductor state=restarted
  service: name=nova-novncproxy state=restarted

- name: remove Nova SQLite DB
  file: path=/var/lib/nova/nova.sqlite state=absent
